const initialData = {
  tasks: {
    "prob-1": {
      id: "prob-1",
      title: "Branch Sums",
      difficulty: "Easy",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-2": {
      id: "prob-2",
      title: "Invert Binary Tree",
      difficulty: "Medium",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-3": {
      id: "prob-3",
      title: "Two Number Sum",
      difficulty: "Easy",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-4": {
      id: "prob-4",
      title: "Validate Subsequence",
      difficulty: "Easy",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-5": {
      id: "prob-5",
      title: "Find Closest Value In BST",
      difficulty: "Easy",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-6": {
      id: "prob-6",
      title: "Same BSTs",
      difficulty: "Hard",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-7": {
      id: "prob-7",
      title: "Depth-first Search",
      difficulty: "Easy",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-8": {
      id: "prob-8",
      title: "Node Depths",
      difficulty: "Easy",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-9": {
      id: "prob-9",
      title: "Binary Search",
      difficulty: "Easy",
      category: "Searching",
      completed: false,
      filter: false,
    },
    "prob-10": {
      id: "prob-10",
      title: "Nth Fibonacci",
      difficulty: "Easy",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-11": {
      id: "prob-11",
      title: "Product Sum",
      difficulty: "Easy",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-12": {
      id: "prob-12",
      title: "Find Three Largest Numbers",
      difficulty: "Easy",
      category: "Searching",
      completed: false,
      filter: false,
    },
    "prob-13": {
      id: "prob-13",
      title: "Bubble Sort",
      difficulty: "Easy",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-14": {
      id: "prob-14",
      title: "Insertion Sort",
      difficulty: "Easy",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-15": {
      id: "prob-15",
      title: "Selection Sort",
      difficulty: "Easy",
      category: "Sorting",
      completed: false,
      filter: false,
    },
  },
  columns: {
    "column-1": {
      id: "column-1",
      title: "Easy",
      taskIds: [
        "prob-1",
        "prob-3",
        "prob-4",
        "prob-5",
        "prob-7",
        "prob-8",
        "prob-9",
        "prob-10",
        "prob-11",
        "prob-12",
        "prob-13",
        "prob-14",
        "prob-15",
      ],
    },
    "column-2": {
      id: "column-2",
      title: "Medium",
      taskIds: ["prob-2"],
    },
    "column-3": {
      id: "column-3",
      title: "Hard",
      taskIds: ["prob-6"],
    },
  },
  columnOrder: ["column-1", "column-2", "column-3"],
  columnsCategoryList: {
    "column-cat-1": {
      id: "column-cat-1",
      title: "Binary Trees",
      taskIds: ["prob-1", "prob-2", "prob-8"],
    },
    "column-cat-2": {
      id: "column-cat-2",
      title: "Arrays",
      taskIds: ["prob-3", "prob-4"],
    },
    "column-cat-3": {
      id: "column-cat-3",
      title: "Binary Search Trees",
      taskIds: ["prob-5", "prob-6"],
    },
    "column-cat-4": {
      id: "column-cat-4",
      title: "Searching",
      taskIds: ["prob-9", "prob-12"],
    },
    "column-cat-5": {
      id: "column-cat-5",
      title: "Recursion",
      taskIds: ["prob-10", "prob-11"],
    },
    "column-cat-6": {
      id: "column-cat-6",
      title: "Sorting",
      taskIds: ["prob-13", "prob-14", "prob-15"],
    },
    "column-cat-7": {
      id: "column-cat-7",
      title: "Graphs",
      taskIds: ["prob-7"],
    },
  },
  columnCategoryOrder: [
    "column-cat-1",
    "column-cat-2",
    "column-cat-3",
    "column-cat-4",
    "column-cat-5",
    "column-cat-6",
    "column-cat-7",
  ],
  sorting: false,
};

export default initialData;
