const initialData = {
  tasks: {
    "prob-1": {
      id: "prob-1",
      title: "Branch Sums",
      difficulty: "Easy",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-2": {
      id: "prob-2",
      title: "Invert Binary Tree",
      difficulty: "Medium",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-3": {
      id: "prob-3",
      title: "Two Number Sum",
      difficulty: "Easy",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-4": {
      id: "prob-4",
      title: "Validate Subsequence",
      difficulty: "Easy",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-5": {
      id: "prob-5",
      title: "Find Closest Value In BST",
      difficulty: "Easy",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-6": {
      id: "prob-6",
      title: "Same BSTs",
      difficulty: "Hard",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-7": {
      id: "prob-7",
      title: "Depth-first Search",
      difficulty: "Easy",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-8": {
      id: "prob-8",
      title: "Node Depths",
      difficulty: "Easy",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-9": {
      id: "prob-9",
      title: "Binary Search",
      difficulty: "Easy",
      category: "Searching",
      completed: false,
      filter: false,
    },
    "prob-10": {
      id: "prob-10",
      title: "Nth Fibonacci",
      difficulty: "Easy",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-11": {
      id: "prob-11",
      title: "Product Sum",
      difficulty: "Easy",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-12": {
      id: "prob-12",
      title: "Find Three Largest Numbers",
      difficulty: "Easy",
      category: "Searching",
      completed: false,
      filter: false,
    },
    "prob-13": {
      id: "prob-13",
      title: "Bubble Sort",
      difficulty: "Easy",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-14": {
      id: "prob-14",
      title: "Insertion Sort",
      difficulty: "Easy",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-15": {
      id: "prob-15",
      title: "Selection Sort",
      difficulty: "Easy",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-16": {
      id: "prob-16",
      title: "Palindrome Check",
      difficulty: "Easy",
      category: "Strings",
      completed: false,
      filter: false,
    },
    "prob-17": {
      id: "prob-17",
      title: "Caesar Cipher Encryptor",
      difficulty: "Easy",
      category: "Strings",
      completed: false,
      filter: false,
    },
    "prob-18": {
      id: "prob-18",
      title: "Three Number Sun",
      difficulty: "Medium",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-19": {
      id: "prob-19",
      title: "Smallest Difference",
      difficulty: "Medium",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-20": {
      id: "prob-20",
      title: "Move Element To End",
      difficulty: "Medium",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-21": {
      id: "prob-21",
      title: "Monotonic Array",
      difficulty: "Medium",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-22": {
      id: "prob-22",
      title: "Spiral Traverse",
      difficulty: "Medium",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-23": {
      id: "prob-23",
      title: "Longest Peak",
      difficulty: "Medium",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-24": {
      id: "prob-24",
      title: "Four Number Sum",
      difficulty: "Hard",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-25": {
      id: "prob-25",
      title: "Subarray Sort",
      difficulty: "Hard",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-26": {
      id: "prob-26",
      title: "Largest Range",
      difficulty: "Hard",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-27": {
      id: "prob-27",
      title: "Min Rewards",
      difficulty: "Hard",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-28": {
      id: "prob-28",
      title: "Zigzag Traverse",
      difficulty: "Hard",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-29": {
      id: "prob-29",
      title: "Apartment Hunting",
      difficulty: "Very Hard",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    "prob-30": {
      id: "prob-30",
      title: "Calendar Matching",
      difficulty: "Very Hard",
      category: "Arrays",
      completed: false,
      filter: false,
    },
    // "prob-31": {
    //   id: "prob-31",
    //   title: "Waterfall Streams",
    //   difficulty: "Very Hard",
    //   category: "Arrays",
    //   completed: false,
    //   filter: false,
    // },
    "prob-32": {
      id: "prob-32",
      title: "BST Construction",
      difficulty: "Medium",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-33": {
      id: "prob-33",
      title: "Validate BST",
      difficulty: "Medium",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-34": {
      id: "prob-34",
      title: "BST Traversal",
      difficulty: "Medium",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-35": {
      id: "prob-35",
      title: "Min Height BST",
      difficulty: "Medium",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-36": {
      id: "prob-36",
      title: "Right Smaller Than",
      difficulty: "Very Hard",
      category: "Binary Search Trees",
      completed: false,
      filter: false,
    },
    "prob-37": {
      id: "prob-37",
      title: "Max Path Sum in Binary Trees",
      difficulty: "Hard",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-38": {
      id: "prob-38",
      title: "Iterative In-order Traversal",
      difficulty: "Very Hard",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-39": {
      id: "prob-39",
      title: "Flatten Binary Tree",
      difficulty: "Very Hard",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-40": {
      id: "prob-40",
      title: "Right Sibling Tree",
      difficulty: "Very Hard",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-41": {
      id: "prob-41",
      title: "All Kind of Node Depths",
      difficulty: "Very Hard",
      category: "Binary Trees",
      completed: false,
      filter: false,
    },
    "prob-42": {
      id: "prob-42",
      title: "Max Subset Sum No Adjacent",
      difficulty: "Medium",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-43": {
      id: "prob-43",
      title: "Number of Ways To Make Change",
      difficulty: "Medium",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-44": {
      id: "prob-44",
      title: "Min Number Of Coins For Change",
      difficulty: "Medium",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-45": {
      id: "prob-45",
      title: "Levenshtein Distance",
      difficulty: "Medium",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-46": {
      id: "prob-46",
      title: "Max Sum Increasing Subsequence",
      difficulty: "Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-47": {
      id: "prob-47",
      title: "Longest Common Subsequence",
      difficulty: "Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-48": {
      id: "prob-48",
      title: "Min Number Of Jumps",
      difficulty: "Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-49": {
      id: "prob-49",
      title: "Water Area",
      difficulty: "Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-50": {
      id: "prob-50",
      title: "Knapsack Problem",
      difficulty: "Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-51": {
      id: "prob-51",
      title: "Disk Stacking",
      difficulty: "Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-52": {
      id: "prob-52",
      title: "Numbers In Pi",
      difficulty: "Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-53": {
      id: "prob-53",
      title: "Max Profit With K Transactions",
      difficulty: "Very Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-54": {
      id: "prob-54",
      title: "Palindrome Partitioning Min Cuts",
      difficulty: "Very Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-55": {
      id: "prob-55",
      title: "Longest Increasing Subsequence",
      difficulty: "Very Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-56": {
      id: "prob-56",
      title: "Longest String Chain",
      difficulty: "Very Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-57": {
      id: "prob-57",
      title: "Square of Zeroes",
      difficulty: "Very Hard",
      category: "Dynamic Programming",
      completed: false,
      filter: false,
    },
    "prob-58": {
      id: "prob-58",
      title: "Kadane's Algorithm",
      difficulty: "Medium",
      category: "Famous Algroithms",
      completed: false,
      filter: false,
    },
    // "prob-59": {
    //   id: "prob-59",
    //   title: "Dijkstra's Algorithm",
    //   difficulty: "Hard",
    //   category: "Famous Algroithms",
    //   completed: false,
    //   filter: false,
    // },
    "prob-60": {
      id: "prob-60",
      title: "Topological Sort",
      difficulty: "Hard",
      category: "Famous Algroithms",
      completed: false,
      filter: false,
    },
    "prob-61": {
      id: "prob-61",
      title: "Knuth-Morris-Pratt Algorithm",
      difficulty: "Very Hard",
      category: "Famous Algroithms",
      completed: false,
      filter: false,
    },
    "prob-62": {
      id: "prob-62",
      title: "Single Cycle Check",
      difficulty: "Medium",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-63": {
      id: "prob-63",
      title: "Breadth-first Search",
      difficulty: "Medium",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-64": {
      id: "prob-64",
      title: "River Sizes",
      difficulty: "Medium",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-65": {
      id: "prob-65",
      title: "Youngest Common Ancestor",
      difficulty: "Medium",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-66": {
      id: "prob-66",
      title: "Boggle Board",
      difficulty: "Hard",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-67": {
      id: "prob-67",
      title: "Rectangle Mania",
      difficulty: "Very Hard",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-68": {
      id: "prob-68",
      title: "Airport Connections",
      difficulty: "Very Hard",
      category: "Graphs",
      completed: false,
      filter: false,
    },
    "prob-69": {
      id: "prob-69",
      title: "Min Heap Construction",
      difficulty: "Medium",
      category: "Heaps",
      completed: false,
      filter: false,
    },
    "prob-70": {
      id: "prob-70",
      title: "Continuous Median",
      difficulty: "Hard",
      category: "Heaps",
      completed: false,
      filter: false,
    },
    "prob-71": {
      id: "prob-71",
      title: "Merge Sorted Arrays",
      difficulty: "Very Hard",
      category: "Heaps",
      completed: false,
      filter: false,
    },
    "prob-72": {
      id: "prob-72",
      title: "Linked List Construction",
      difficulty: "Medium",
      category: "Linked Lists",
      completed: false,
      filter: false,
    },
    "prob-73": {
      id: "prob-73",
      title: "Remove Kth Node From End",
      difficulty: "Medium",
      category: "Linked Lists",
      completed: false,
      filter: false,
    },
    "prob-74": {
      id: "prob-74",
      title: "Find Loop",
      difficulty: "Hard",
      category: "Linked Lists",
      completed: false,
      filter: false,
    },
    "prob-75": {
      id: "prob-75",
      title: "Reverse Linked List",
      difficulty: "Hard",
      category: "Linked Lists",
      completed: false,
      filter: false,
    },
    "prob-76": {
      id: "prob-76",
      title: "Merge Linked Lists",
      difficulty: "Hard",
      category: "Linked Lists",
      completed: false,
      filter: false,
    },
    "prob-77": {
      id: "prob-77",
      title: "Shift Linked List",
      difficulty: "Hard",
      category: "Linked Lists",
      completed: false,
      filter: false,
    },
    "prob-78": {
      id: "prob-78",
      title: "LRU Cache",
      difficulty: "Very Hard",
      category: "Linked Lists",
      completed: false,
      filter: false,
    },
    "prob-79": {
      id: "prob-79",
      title: "Rearrange Linked LIst",
      difficulty: "Very Hard",
      category: "Linked Lists",
      completed: false,
      filter: false,
    },
    "prob-80": {
      id: "prob-80",
      title: "Permutations",
      difficulty: "Medium",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-81": {
      id: "prob-81",
      title: "Powerset",
      difficulty: "Medium",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-82": {
      id: "prob-82",
      title: "Lowest Common Manager",
      difficulty: "Hard",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-83": {
      id: "prob-83",
      title: "Interweaving Strings",
      difficulty: "Hard",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-84": {
      id: "prob-84",
      title: "Number Of Binary Tree Topologies",
      difficulty: "Very Hard",
      category: "Recursion",
      completed: false,
      filter: false,
    },
    "prob-85": {
      id: "prob-85",
      title: "Search In Sorted Matrix",
      difficulty: "Medium",
      category: "Searching",
      completed: false,
      filter: false,
    },
    "prob-86": {
      id: "prob-86",
      title: "Shifted Binary Search",
      difficulty: "Hard",
      category: "Searching",
      completed: false,
      filter: false,
    },
    "prob-87": {
      id: "prob-87",
      title: "Search For Range",
      difficulty: "Hard",
      category: "Searching",
      completed: false,
      filter: false,
    },
    "prob-88": {
      id: "prob-88",
      title: "Quickselect",
      difficulty: "Hard",
      category: "Searching",
      completed: false,
      filter: false,
    },
    "prob-89": {
      id: "prob-89",
      title: "Quick Sort",
      difficulty: "Hard",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-90": {
      id: "prob-90",
      title: "Heap Sort",
      difficulty: "Hard",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-91": {
      id: "prob-91",
      title: "Merge Sort",
      difficulty: "Very Hard",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-92": {
      id: "prob-92",
      title: "Min Max Stack Construction",
      difficulty: "Medium",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-93": {
      id: "prob-93",
      title: "Balanced Brackets",
      difficulty: "Medium",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-94": {
      id: "prob-94",
      title: "Shorten Path",
      difficulty: "Very Hard",
      category: "Sorting",
      completed: false,
      filter: false,
    },
    "prob-95": {
      id: "prob-95",
      title: "Longest Palindromic Substring",
      difficulty: "Medium",
      category: "Strings",
      completed: false,
      filter: false,
    },
    "prob-96": {
      id: "prob-96",
      title: "Group Anagrams",
      difficulty: "Medium",
      category: "Strings",
      completed: false,
      filter: false,
    },
    "prob-97": {
      id: "prob-97",
      title: "Longest Substring Without Duplication",
      difficulty: "Hard",
      category: "Strings",
      completed: false,
      filter: false,
    },
    "prob-98": {
      id: "prob-98",
      title: "Underscorify Substring",
      difficulty: "Hard",
      category: "Strings",
      completed: false,
      filter: false,
    },
    "prob-99": {
      id: "prob-99",
      title: "Pattern Matcher",
      difficulty: "Hard",
      category: "Strings",
      completed: false,
      filter: false,
    },
    "prob-100": {
      id: "prob-100",
      title: "Smallest Substring Container",
      difficulty: "Very Hard",
      category: "Strings",
      completed: false,
      filter: false,
    },
    "prob-101": {
      id: "prob-101",
      title: "Suffix Trie Constructrion",
      difficulty: "Medium",
      category: "Tries",
      completed: false,
      filter: false,
    },
    "prob-102": {
      id: "prob-102",
      title: "Multi String Search",
      difficulty: "Hard",
      category: "Tries",
      completed: false,
      filter: false,
    },

  },
  columns: {
    "column-1": {
      id: "column-1",
      title: "Easy",
      taskIds: [
        "prob-1",
        "prob-3",
        "prob-4",
        "prob-5",
        "prob-7",
        "prob-8",
        "prob-9",
        "prob-10",
        "prob-11",
        "prob-12",
        "prob-13",
        "prob-14",
        "prob-15",
        "prob-16",
        "prob-17"
      ],
    },
    "column-2": {
      id: "column-2",
      title: "Medium",
      taskIds: ["prob-2", "prob-18", "prob-19", "prob-20", "prob-21", "prob-22", "prob-23","prob-32","prob-33","prob-34","prob-35","prob-42","prob-43","prob-44","prob-45","prob-58","prob-62","prob-63","prob-64","prob-65","prob-69","prob-72","prob-73","prob-80","prob-81","prob-85","prob-92","prob-93","prob-95","prob-96","prob-101"],
    },
    "column-3": {
      id: "column-3",
      title: "Hard",
      taskIds: ["prob-6","prob-24","prob-25","prob-26","prob-27","prob-28","prob-37","prob-46","prob-47","prob-48","prob-49","prob-50","prob-51","prob-52","prob-60","prob-66","prob-70","prob-74","prob-75","prob-76","prob-77","prob-82","prob-83","prob-86","prob-87","prob-88","prob-89","prob-90","prob-97","prob-98","prob-99","prob-102"],
    },
    "column-4": {
      title: "Very Hard",
      taskIds: ["prob-29","prob-30","prob-36","prob-38","prob-39","prob-40","prob-41","prob-53","prob-54","prob-55","prob-56","prob-57","prob-61","prob-67","prob-68","prob-71","prob-78","prob-79","prob-84","prob-91","prob-94","prob-100"]
    }
  },
  columnOrder: ["column-1", "column-2", "column-3","column-4"],
  columnsCategoryList: {
    "column-cat-1": {
      id: "column-cat-1",
      title: "Binary Trees",
      taskIds: ["prob-1", "prob-8", "prob-2","prob-37","prob-38","prob-39","prob-40", "prob-41"],
    },
    "column-cat-2": {
      id: "column-cat-2",
      title: "Arrays",
      taskIds: ["prob-3", "prob-4", "prob-18", "prob-19", "prob-20", "prob-21", "prob-22", "prob-23", "prob-24","prob-25","prob-26","prob-27","prob-28","prob-29","prob-30",],
    },
    "column-cat-3": {
      id: "column-cat-3",
      title: "Binary Search Trees",
      taskIds: ["prob-5","prob-32", "prob-33","prob-34","prob-35","prob-6","prob-36"],
    },
    "column-cat-4": {
      id: "column-cat-4",
      title: "Searching",
      taskIds: ["prob-9", "prob-12","prob-85","prob-86","prob-87","prob-88",],
    },
    "column-cat-5": {
      id: "column-cat-5",
      title: "Recursion",
      taskIds: ["prob-10", "prob-11","prob-80","prob-81","prob-82","prob-83","prob-84"],
    },
    "column-cat-6": {
      id: "column-cat-6",
      title: "Sorting",
      taskIds: ["prob-13", "prob-14", "prob-15","prob-89","prob-90","prob-91",],
    },
    "column-cat-7": {
      id: "column-cat-7",
      title: "Graphs",
      taskIds: ["prob-7","prob-62","prob-63","prob-64","prob-65","prob-66","prob-67","prob-68",],
    },
    "column-cat-8": {
      id: "column-cat-8",
      title: "Strings",
      taskIds: ["prob-16", "prob-17","prob-95","prob-96","prob-97","prob-98","prob-99","prob-100"],
    },
    "column-cat-9": {
      id: "column-cat-9",
      title: "Dynamic Programming",
      taskIds: ["prob-42","prob-43","prob-44","prob-45","prob-46","prob-47","prob-48","prob-49","prob-50","prob-51","prob-52","prob-53","prob-54","prob-55","prob-56","prob-57"],
    },
    "column-cat-10": {
      id: "column-cat-10",
      title: "Famous Algorithms",
      taskIds: ["prob-58","prob-60","prob-61"],
    },
    "column-cat-11": {
      id: "column-cat-11",
      title: "Heaps",
      taskIds: ["prob-69","prob-70","prob-71"],
    },
    "column-cat-12": {
      id: "column-cat-12",
      title: "Linked Lists",
      taskIds: ["prob-72","prob-73","prob-74","prob-75","prob-76","prob-77","prob-78","prob-79",],
    },
    "column-cat-13": {
      id: "column-cat-13",
      title: "Stacks",
      taskIds: ["prob-92","prob-93","prob-94",],
    },
    "column-cat-14": {
      id: "column-cat-14",
      title: "Tries",
      taskIds: ["prob-101","prob-102",],
    },
  },
  columnCategoryOrder: [
    "column-cat-1",
    "column-cat-2",
    "column-cat-3",
    "column-cat-4",
    "column-cat-5",
    "column-cat-6",
    "column-cat-7",
    "column-cat-8",
    "column-cat-9",
    "column-cat-10",
    "column-cat-11",
    "column-cat-12",
    "column-cat-13",
    "column-cat-14",
  ],
  sorting: false,
};

export default initialData;
